POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fName":"bebudi",
    "lName":"baral",
    "email": "saugat@gmail.com",
    "password":"123456789"
    
}


###
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "saugat@gmail.com",
    "password":"123456789"
    
}

# exercise router
###
POST http://localhost:8000/api/v1/exercise
Content-Type: application/json


    {"exerciseName": "bench press", "exerciseType":"chest"}


### 
POST http://localhost:8000/api/v1/workoutplanner
Content-Type: application/json


   {
  "workOutPlannerName": "Complete Weekly Workout Plan",
  "refreshJWT": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdWdhdEBnbWFpbC5jb20iLCJpYXQiOjE3NzIxNTc1NjksImV4cCI6MTc3MjI0Mzk2OX0.NmL1raqjQ3xJInPfeNSscb6iTVbgdigAEwv9gDIQLYk"
 
   }
###


GET http://localhost:8000/api/v1/workoutplanner/user/6970a5efc028a1d37d2048bd/workoutplan/698e8ac090c1aff136f4ee33




###
GET http://localhost:8000/api/v1/workoutplanner/user/6970a5efc028a1d37d2048bd



###
POST http://localhost:8000/api/v1/workoutlog
Content-Type: application/json

{"workoutPlanId":"adfjkaldfas"}