POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "fName":"bebudi",
    "lName":"baral",
    "email": "saugat@gmail.com",
    "password":"123456789"
    
}


###
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email": "saugat@gmail.com",
    "password":"123456789"
    
}

# exercise router
###
POST http://localhost:8000/api/v1/exercise
Content-Type: application/json


    {"exerciseName": "bench press", "exerciseType":"chest"}


### 
POST http://localhost:8000/api/v1/workoutplanner
Content-Type: application/json


    {"workOutPlannerName": "my workout plan", "refreshJWT":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdWdhdEBnbWFpbC5jb20iLCJpYXQiOjE3NzEzMjkwMzMsImV4cCI6MTc3MTQxNTQzM30.wi4LZ-YKqRQVen9kmh3WHUUMmXpzrDq18UCsyACSoUA"
, "exerciseName": "Incline Dumbbell Press"

    }




###


GET http://localhost:8000/api/v1/workoutplanner/user/6970a5efc028a1d37d2048bd/workoutplan/698e8ac090c1aff136f4ee33




###
GET http://localhost:8000/api/v1/workoutplanner/user/69943a91679808ca5d040251